### ISSUE TITLE
Issue with 5.3.2 - Scroll to Tiddler Does Not Work

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-uglify#12]
When click on a link in Open tab, or when click on a link in story river, TW does not scroll to the tiddler its title clicked.

**Comment by flibbles** [comment]
I'm looking into this. The resolution of this issue will be tied closely to the outcome of https://github.com/Jermolene/TiddlyWiki5/pull/7888.

**Comment by flibbles** [comment]
I've released v1.8.0 which has full support for Tiddlywiki 5.3.2, including support for the bug that Tiddlywiki introduced.

I recommend migrating to Tiddlywiki 5.3.3 as soon as it releases because the workaround for the core bug means Uglify has to forgo some compression it'd ordinarily want to do.

**Comment by kookma** [comment]
I moved to TW 5.3.3 and Uglify 1.8.0. I will report if I find any issue.
Thank you for all your efforts.

**Comment by flibbles** [comment]
Thank you! It should all work, but sometimes problems sneak past the unit tests.

(Uglify 1.8.1 trims off an extra 6k from the javascript too. Almost 0.5% of the file size!)
